### ISSUE TITLE
request to maintain cellpose feedstock

### ISSUE THREAD

**Issue by carsen-stringer** [conda-forge/cellpose-feedstock#17]
### Comment:

Hi I am one of the main developers of [cellpose](https://github.com/MouseLand/cellpose), would it be possible for me to be a maintainer of this feedstock? Thanks for your help

**Comment by xhochy** [comment]
Please make a PR that updates the feedstock to its latest version and add yourself as a maintainer as part of this PR. Then we're happy to merge.

**Comment by carsen-stringer** [comment]
thanks very much @xhochy for your help, we made the PR

**Comment by bgruening** [comment]
Thanks for maintaining
